name: run_native_process_with_dart
description: A simple console application.
version: 0.0.1
#homepage: https://www.example.com
author: easonp <easonp.dev@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args:

#dev_dependencies:
#  test: ^0.12.0
